package com.wbb.mapper;

import com.wbb.bean.Cost;

public interface CostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Sat Jul 21 10:40:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Sat Jul 21 10:40:05 CST 2018
     */
    int insert(Cost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Sat Jul 21 10:40:05 CST 2018
     */
    int insertSelective(Cost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Sat Jul 21 10:40:05 CST 2018
     */
    Cost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Sat Jul 21 10:40:05 CST 2018
     */
    int updateByPrimaryKeySelective(Cost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Sat Jul 21 10:40:05 CST 2018
     */
    int updateByPrimaryKey(Cost record);
    
    int sum();
}